language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: xenial # legacy opencv2
      addons:
        apt:
          update: true
          packages:
            - libopencv-dev
            - opencv-data
    - dist: xenial # up-to-date 3.4 branch
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:cran/opencv'
          packages:
            - libopencv-dev
            - opencv-data
    - dist: xenial # 3.2 branch (Bionic / Buster)
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:cran/opencv-3.2'
          packages:
            - libopencv-dev
            - libopencv-shape-dev
            - opencv-data
    - os: osx
      brew_packages: opencv@3
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv@3/lib/pkgconfig"
    - os: osx
      brew_packages: opencv@2
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv@2/lib/pkgconfig"
    - os: osx
      brew_packages: opencv
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
