language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: bionic
      addons:
        apt:
          packages:
            - libopencv-dev
            - opencv-data
    - dist: bionic # backported 4.2 branch
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:cran/opencv-4.2'
          packages:
            - libopencv-dev
            - opencv-data
    - dist: xenial # backported 3.4 branch
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:cran/opencv'
          packages:
            - libopencv-dev
            - opencv-data
    - dist: xenial # backported 3.2 branch (Bionic / Buster)
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:cran/opencv-3.2'
          packages:
            - libopencv-dev
            - libopencv-shape-dev
            - opencv-data
    - os: osx
      brew_packages: opencv
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv/lib/pkgconfig"
    - os: osx
      brew_packages: opencv@3
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv@3/lib/pkgconfig"
    - os: osx
      brew_packages: opencv@2
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv@2/lib/pkgconfig"
    - os: osx
      brew_packages: opencv
    - os: osx
      osx_image: xcode11.4
      disable_homebrew: true
      r_check_args: ""
    - os: osx
      osx_image: xcode10.1
      disable_homebrew: true
      r_check_args: ""
    - r: 3.6
      os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
      r_check_args: ""
